guilds:
  - 1746358743
quotes_channel: 3745834657864387563487
upvote_emoji_name: "Miaumiau"
upvote_emoji_id: 784556874365
downvote_emoji_name: "Miaumiau2"
downvote_emoji_id: 78455687476
quote_permission_role: 73567863478563487
sis_api_token: ""
sis_api_endpoint: "https://example.com"